### PR TITLE
added quick & dirty __repr__ methods

### PR DESCRIPTION
**Pull request by snake-biscuits**
makes some short strings for skimming through parsed fgds fast

### CODE REVIEW

**Comment by maxdup** [comment]
I will ignore changes on parser.py since they are no longer relevant.
The repr functions are cool but they should be documented; their purpose should be consistent and explicit. (I will add some instructions on building the documentation with sphinx in the readme shortly).
Also repr functions should abide by these guidelines https://docs.python.org/3/reference/datamodel.html#object.__repr__

**Comment by snake-biscuits** [comment]
`<ClassName __repr__>` looks like the best option to me,
I'll take a look at Sphinx at some point and then do a proper refactor.

Also, were you planning to support a range of python versions?
I'd really like to use f-strings as I find them to be more pythonic, but they're only in python 3.6+

I'll also put a bit more thought into which data to show as I keep developing an entity editor for QtPyHammer.

I hope that meets all the requirements you just set (and if you've got other ideas / counter points please do let me know!)
Also sorry if I mess up later down the line with commits etc, this is my first proper pull request, still very much learning all the ins and outs of Github.

**Comment by maxdup** [comment]
I will probably look into the reprs today and see if I can get something down.

I was going to make a test suite with tox to figure out what python3 versions are currently supported and eventually look into [python-future's pasteurize](https://python-future.org/pasteurize.html) to increase support to python2. Until I have that set up, I would refrain from using f-strings.

**Comment by maxdup** [comment]
So I've took on where you left off and implemented repr methods for all classes, let me know if they don't meet your needs or if anything needs to be improved.

**Comment by snake-biscuits** [comment]
Looks like everything I need and more, thanks!

**Pull request merged**
